from pathlib import Path
import ast,json,re,base64,shutil
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase.pdfmetrics import stringWidth
base=Path('process-comp/build.py').read_text();base=base[:base.index('line(50,40,1582,40)')];base=base.replace("P=Path(__file__).parent; W,H=1632,1056","P=Path('editorial-deck'); W,H=1632,1056").replace("P/'DraftDeck_Process_Comp.pdf'","P/'BOSS_Day_Zero_Editorial_v0.3.pdf'");exec(base)
# Extract approved working copy and narrative titles from the earlier deck.
old=ast.parse(Path('podcast-deck/build.py').read_text());slides={};cur=0
for node in old.body:
 if isinstance(node,ast.Expr) and isinstance(node.value,ast.Call):
  q=node.value;name=getattr(q.func,'id','')
  if name=='start':
   a=[ast.literal_eval(x) for x in q.args];cur=a[0];slides[cur]={'title':a[1],'kind':a[2],'time':a[3],'lead':a[4],'blocks':[]}
  elif name=='section' and cur:
   a=[ast.literal_eval(x) for x in q.args];slides[cur]['blocks'].append((a[2],a[3],a[4]))
# Low-density page copy.
low={
1:[('FRAME','A bounded task travels with its source.','Identify what enters the workflow, who may act, where the result belongs, and what evidence establishes completion. A confident answer is not a receipt. The shared frame makes those requirements explicit before you inspect a returned result.'),('EVIDENCE','Keep three claims separate.','Arrival records delivery. Inspection compares content with criteria. Release requires authorization covering the artifact, action, and destination. Begin manually so each boundary is visible; automate suitable steps after the process is understood.')],
3:[('SENDER','Prepare the agreement.','Supply the source, identified version, objective, permitted actions, constraints, and return format.'),('PAYLOAD','Carry actual context.','A second chat does not inherit the first chat’s memory. The frame and source must travel together.'),('RECEIVER','Confirm the boundary.','The frame does not create access or capability. Confirm readability and authorization for the affected task. Missing required source pauses dependent work; independent authorized work can continue.')],
7:[('PREPARE','Draft in Chat A.','Create a read-only inventory request using the shared frame and practice source.'),('TRANSFER','Carry to Chat B.','Paste the complete frame and source. Save the exact request you sent. Do not assume context transfers automatically.'),('COMPARE','Bring back the evidence.','Return the exact response and inspect it against the source. Record checks and unknowns. Keep the source comparison as part of the evidence package rather than treating agreement between chats as correctness.')],
9:[('OMIT','Send the frame without the source.','Use a separate attempt. Observe whether the receiver requests input, fabricates details, or returns incomplete work. These are possible behaviors, not guaranteed results.'),('RECOVER','Supply what is required.','Record the actual response. Supply the missing practice source and repeat the bounded request.'),('RECHECK','Compare again.','Inspect the new response against the source. Recover affected work without duplicating completed steps. Preserve the missing-input attempt and recovery record.')],
11:[('ATTEMPT','A capability gap was discovered.','Programmatic Audio Overview generation was unsupported during an attempted action. This is a reported production example, not an observed pre-action capability check.'),('SCOPE','Check the alternative route.','Confirm that existing authorization covers the new tool, action, and destination. Additional authorization is needed where scope expands.'),('REROUTE','Use the supported interface.','The activity moved to the web interface. Checking capability earlier is the proposed improvement. Reported import success does not establish full-text fidelity.')],
14:[('VERIFY','Compare content with criteria.','Identify the source anchors, acceptance checks, verifier, and limitations. If checks do not pass or evidence is insufficient, hold the affected result for review.'),('AUTHORIZE','Check release scope.','VERIFIED does not grant permission to deploy, publish, or forward. Existing explicit authorization may already cover release; additional authorization is needed only when scope expands.'),('RELEASE','Record the actual action.','Check the artifact, action, and exact destination. Evaluate visual and content acceptance separately. A polished artifact can still fail content checks.')]
}
# New medium-copy sections add explicit relationships instead of filler illustrations.
extra={
2:('BOUNDARY','Trace one handoff','Suppose a receiving system returns a clean workshop summary. The title and materials match, but the room number was supplied without a source. The response may look useful while failing the preservation rule. The governor identifies the deviation using the frame, not the model’s tone. Keep known facts separate from interpretations and unknowns. Decide which action can continue, which needs recovery, and what evidence would resolve the gap. This is the difference between getting an answer and establishing an inspectable result.'),
5:('ENFORCEMENT','Separate instructions from controls','Written permissions describe what the executor is allowed to do. Active access controls can enforce limits in a connected system. Neither guarantees correct content. An executor might have a tool available but lack authorization for the requested destination. Another might be authorized yet unable to access the required source. Inspect these conditions independently. Before changing a document, sending a payload, or publishing a result, check scope for that specific action. Keep the returned evidence tied to the same objective and source version used in the request.'),
6:('ACCEPTANCE','Use the source as the comparator','The missing room value is not the same as a missing source document. The supplied document contains enough evidence to inventory the known details and explicitly report the absent field. If the document itself is missing, the executor cannot extract its facts. Pause that dependent action and request the payload. Define completion as the required inventory and explicit unknown, not a fully populated schedule. Do not invent a calendar date from Saturday. Preserve source wording where the request requires exact extraction, and save the comparison that establishes acceptance.'),
10:('CLAIM','Match the receipt to its scope','The locked-package analogy explains access, not proof of correctness. Receiving a package establishes arrival. Reading its label establishes metadata visibility. Opening it establishes some access to contents. Inspection must still compare those contents with the expected source. A record that one document was accepted does not establish that every document was imported. Name which source was checked, what was visible, and what remains unknown. Preserve recovery details so later automation can handle the same format boundary without repeating already completed work.'),
12:('IMPLEMENTATION','Keep acceptance checks attached','Automating transfer changes the transport mechanism, not the required evidence. A destination selection becomes a tool or API route. Copying becomes payload transport. Permission statements define scope; access controls may enforce it. Comparison becomes a validation check. Run identifiers, duplicate detection, bounded retries, and logs require implementation rather than appearing automatically. A retry should address the affected operation without repeating successful writes. Keep the source version and returned result associated with the same run. When evidence is incomplete, report the limit instead of silently upgrading the status.'),
13:('SELECTION','Assign the step deliberately','A workflow may combine all four mechanisms or use only the ones required. Choose interpretation when the task needs reasoning about supplied content. Choose explicit rules when a condition has a defined test. Use an interface when an authorized system must communicate or act. Use configured execution when prescribed interactions fit the application. Then inspect the result against the same acceptance criteria. Model output is not an external action, and successful execution is not proof of source fidelity. The learner continues to govern objective, scope, and evidence.')
}
# Dense reference pages: explicit entries, not a wall of undifferentiated text.
fields=[('Run ID','Give each execution a unique reference so the request, source, returned result, and recovery record can be associated. The identifier supports traceability; it does not prove correctness.'),('Observable objective','State a result that can be inspected. For the workshop example, extract title, schedule, materials, and unknowns from the supplied source. Avoid objectives whose completion depends only on a confident claim.'),('Actual inputs & versions','Identify the source material and version used for the run. Pin a version where supported; record limitations where it cannot be pinned. A filename alone does not establish readable content.'),('Exact destination','Name the receiving chat or resource precisely. Authorization applies to the affected action and destination. Moving the payload to another interface does not automatically authorize its receipt, modification, or release.'),('Necessary definitions','Define terms needed to interpret the task. Inventory means reporting the required source facts and missing details within the stated preservation rule. Definitions prevent the receiver from silently choosing a different meaning.'),('Permitted actions','State the work that falls within scope, such as reading the source and returning an inventory. Capability is separate: having a tool available does not authorize its use for every action.'),('Constraints','Specify prohibitions and preservation requirements. Do not invent a room number, date, location, or organizer. Do not silently correct extracted wording when the task requires exact source preservation.'),('Unknowns','Record absent, unreadable, or unverified information. An unknown room value may remain explicit while the inventory completes. Missing required source content pauses the action that depends on that source.'),('Completion criteria','Name the acceptance checks that establish the result. Compare title, schedule, materials, and unknowns with the source. Record the verifier and limitations. Execution status alone does not establish those checks.'),('Return format','Specify the required structure, such as a key-value inventory with source excerpts and an explicit unknown label. Formatting supports inspection but does not replace verification. Save the actual returned response.')]
states=[('RECEIVED','The payload arrived at the destination. A receipt supports this arrival claim. It does not prove that required contents are readable, that the source was preserved, or that the requested task completed. Record what actually arrived and identify the destination.'),('READABLE','The executor can access the required content. Reading a filename is metadata visibility, not content access. Ask for evidence appropriate to the task. If only some portions are visible, record that limit rather than treating it as exhaustive source access.'),('IMPORTED','Destination acceptance was reported. This status applies when content is accepted into a receiving resource. It does not automatically establish complete fidelity. A reported successful import needs destination evidence before stronger claims about preservation or correctness can be made.'),('VERIFIED','The named evidence checks passed and the verifier is identified. Compare the output with source anchors and completion criteria. Keep the verification scope explicit. Passing checks does not authorize external release; authorization must cover the artifact, action, and destination.'),('PARTIAL','Required work remains. Interruption, unsupported capability, unfinished extraction, or incomplete verification may leave a task partial without an attempted operation failure. Identify completed work and affected work separately, then recover only the portion that still requires attention.'),('FAILED','An attempted operation failed. Record which action was attempted, what failure was observed, and what evidence supports that description. Do not label missing information as an execution failure. Recovery may reroute the operation within existing authorization or require expanded scope.'),('UNKNOWN','Evidence is insufficient to establish the claim. This may describe an absent room number or unverified destination content. It is distinct from FAILED. Do not substitute fluency or agreement between models for missing facts. Name what evidence would resolve the uncertainty.')]
evidence=[('Shared frame','Submit the actual ten-field agreement used for the run. Preserve the objective, source identifiers, destination, permitted actions, constraints, unknowns, acceptance checks, and return format. This is the comparator for the handoff, not a retrospective statement that everything went well.'),('Sent request','Keep the exact request carried to the receiving system, including the source payload actually supplied. A planned request is not evidence of delivery. If a missing-input attempt was intentional, identify it separately so the complete request and the failure exercise remain distinguishable.'),('Returned response','Save the exact response returned by the receiving executor. Do not replace it with a polished summary before inspection. Identify claims that came from the source, interpretations introduced by the model, and missing information. Confident wording does not establish factual preservation.'),('Source comparison','Record the checks performed against the identified source version. Name the verifier, the acceptance criteria, and the observed results. Separate visual acceptance from content acceptance. A clean diagram or well-formatted inventory can still omit required content or include fabricated details.'),('Recovery record','Describe the missing input, unreadable format, unsupported capability, or failed operation actually observed. Record what changed and what was rechecked. Recover affected steps without repeating successful work. Confirm that authorization covers any alternative tool, action, and destination before proceeding.'),('Unresolved questions','List what remains unknown and what evidence could resolve it. A manual rehearsal establishes observations within the tested environment; it does not prove production behavior. Future integrations need their own capability, authorization, transport, and acceptance checks. Agreement between models remains insufficient proof of correctness.')]
levels={i:('low' if i in low else 'high' if i in (4,8,15) else 'medium') for i in range(1,16)}
features={1: ('AT THE LOADING DOCK', 'A parcel arrives sealed. What evidence establishes arrival, readability, and correct contents?'), 2: ('PAUSE & CONSIDER', 'Which part of your last AI response came from the source, and which part was inferred?'), 3: ('CARRY FORWARD', 'Principle: context must travel. Next action: attach the source and frame to the receiving request.'), 4: ('THE WORKING AGREEMENT', 'Before transfer, identify the actual source version and exact receiver. Keep all ten fields inspectable.'), 5: ('CHOOSE THE ROUTE', 'A tool is available, but destination authorization is unclear. Hold the affected action and resolve its scope.'), 6: ('INSPECT THE PAYLOAD', 'Source: room number not supplied. Candidate: Room 204. Finding: unsupported addition; preserve UNKNOWN.'), 7: ('TRY THE HANDOFF', 'Carry the complete workshop source and frame to a second chat. Save the exact request and response.'), 8: ('EVIDENCE WINDOW', 'Claim: VERIFIED. Required support: named acceptance checks, observed results, verifier, and verification limits.'), 9: ('RECOVERY RECORD', 'Observed problem: source omitted. Action: supply source. Evidence: compare the new response and retain both attempts.'), 10: ('EVIDENCE WINDOW', 'Reported relay: filenames visible; contents inaccessible. Scope: metadata access, not established readability.'), 11: ('CHOOSE THE ROUTE', 'Unsupported capability: select a supported route only within authorization. Earlier capability checking is proposed.'), 12: ('CARRY FORWARD', 'Principle: automate transport and preserve acceptance checks. Next action: identify the check each transfer must carry.'), 13: ('PAUSE & CONSIDER', 'Does this step need interpretation, a rule, an interface, or configured execution? What evidence tests the result?'), 14: ('BEFORE YOU RELEASE', 'Check 1: content and visual acceptance. Check 2: authorization covers this artifact, action, and exact destination.'), 15: ('TRY THE HANDOFF', 'Submit frame, request, response, comparison, recovery record, and unresolved questions. Identify the next bounded trial.')}
pages=[];manifest=[]
artpath=Path('podcast-deck/logistics-art.png');art64=base64.b64encode(artpath.read_bytes()).decode()
def finish(n):
 global svg,texts
 label,prompt=features[n]
 line(50,870,1582,870);line(50,885,50,977,'#B34700')
 text(72,886,label,15,True,col='#B34700')
 text(72,920,prompt,19,width=1450)
 line(72,984,1582,984,'#B9BFC4')
 text(50,1015,f'BOSS / DAY ZERO / {levels[n].upper()} COPY / {n:02d} OF 15 / REVIEW CANDIDATE',12)
 art='<svg xmlns="http://www.w3.org/2000/svg" width="1632" height="1056" viewBox="0 0 1632 1056">'+''.join(svg)+'</svg>'
 (P/f'geometry-{n:02d}.svg').write_text(art)
 pages.append('<section class="page" data-document-role="page"><div class="diagram">'+art+'</div>'+''.join(texts)+'</section>');c.showPage()
 if n<15:c.scale(.75,.75)
def wordcount(blocks):return sum(len(re.findall(r"\S+",' '.join(b))) for b in blocks)
prompts={1:'Where does your workflow trust confidence without evidence?',2:'Which boundary makes your next request inspectable?',3:'What context must travel with the payload?',4:'Which shared-frame field do you usually leave implicit?',5:'Write one permitted action and one constraint.',6:'What would you preserve as UNKNOWN?',7:'Where could context disappear in your manual relay?',8:'What evidence supports the status you assigned?',9:'What changed after you supplied the missing input?',10:'Which claim can you support from the retrieved evidence?',11:'Which capability can you check before the affected action?',12:'Which acceptance check must survive automation?',13:'Which mechanism fits your next step?',14:'Does release authorization cover this artifact and destination?',15:'What remains unresolved before the next integration?'}
for n in range(1,16):
 svg=[];texts=[];s=slides[n];level=levels[n]
 line(50,40,1582,40);text(50,53,'BOSS / BIOSCILLATE OPERATING SYSTEM BY SEVEN',13);text(1200,53,f'{level.upper()} / {n:02d}',13)
 size=44
 while stringWidth(s['title'],'CopyBold',size)>1520:size-=1
 text(50,102,s['title'],size,True);text(50,171,s['lead'],22,width=1490)
 if level!='high' and n!=1:text(50,232,'READING GUIDE / Connectors show topic order, not automatic execution.',13,col='#697177')
 if level=='low':
  blocks=low[n]
  if n==1:
   c.drawImage(ImageReader(str(artpath)),60,H-265-395,width=1512,height=395,preserveAspectRatio=True,anchor='c',mask='auto');texts.append(f'<img class="story" style="left:60px;top:265px;width:1512px;height:395px" src="data:image/png;base64,{art64}" alt="Logistics opener">')
   for i,(a,b,body) in enumerate(blocks):
    x=60+i*800;text(x,678,a,14,True,col='#B34700');text(x,710,b,24,True,width=700);text(x,754,body,17,width=700)
  else:
   for i,(a,b,body) in enumerate(blocks):
    y=285+i*180;rect(60,y,350,120);text(80,y+20,a,23,True);text(80,y+64,b,18,width=307);line(410,y+55,475,y+55,'#B34700');text(495,y+8,body,23,width=1030)
    if i<len(blocks)-1:arrow([(235,y+120),(235,y+175)])
   # These arrows denote reading order, not unconditional execution.
 elif level=='medium':
  blocks=s['blocks']
  if n==12:
   blocks=[('ROUTE','Select the receiver','Choosing a receiving chat corresponds to selecting the destination and tool route. Carry source text as an identified payload. The frame defines the objective and permitted actions; it does not create access, shared memory, or functional capability. Check what the receiving executor can actually use before the affected task proceeds.'),('CHECK','Preserve scope and acceptance','Stating permitted actions corresponds to defining authorization scope. Active controls may enforce those limits. Comparing returned output with the source corresponds to validation against named criteria. Automated transport must preserve the same distinctions between receipt, readability, acceptance, and verification. None of those events alone grants release permission.')]
  if n==13:
   blocks=[('REASON','AI and explicit rules','AI can support interpretation and probabilistic reasoning about supplied content. Rules evaluate explicit conditions and deterministic logic. These mechanisms may work together within one activity, but the acceptance checks must remain inspectable. Do not treat fluent model output as evidence that a system action occurred. Missing facts remain missing even when a plausible explanation is available.'),('ACT','APIs and configured execution','APIs provide interfaces through which authorized tools or systems may act. RPA executes configured interactions. Choose the mechanism that fits the task and application. Availability does not grant authority, and successful execution does not prove source fidelity. Record the action performed, the destination, and the returned evidence before assigning a stronger status.')]
  blocks=blocks[:2]+[extra[n]]
  additions=[" Preserve the task agreement used for this run. If the returned result changes the objective, identify that change before treating the response as completion. Record what was actually supplied."," Keep the affected action tied to its exact destination. A tool that can perform the operation still needs authorization within scope. Record limitations instead of implying that access establishes authority."," Compare the final response with the source again after recovery. Save the observed result and unresolved questions. A proposed improvement describes the next workflow; it does not rewrite what happened."]
  blocks=[(a,b,body+additions[i]) for i,(a,b,body) in enumerate(blocks)]
  # diagram aligns each node to the matching copy section, alternating page sides.
  right=n in (5,10,13)
  for i,(a,b,body) in enumerate(blocks):
   y=275+i*192;dx=1200 if right else 60;tx=60 if right else 445;tw=1090 if right else 1110
   rect(dx,y+2,330,127);text(dx+18,y+18,a,18,True,col='#B34700');text(dx+18,y+57,b,20,True,width=292)
   if right:line(1158,y+60,1200,y+60,'#B34700')
   else:line(390,y+60,427,y+60,'#B34700')
   text(tx,y+5,body,18,width=tw)
   if i<2:arrow([(dx+165,y+129),(dx+165,y+186)])
 else:
  entries=fields if n==4 else states if n==8 else evidence
  intro={'4':'Each field answers a distinct question. Read the specification as a complete agreement rather than a collection of optional suggestions. Preserve the frame used in the actual run so the returned result can be inspected against the same task boundaries.','8':'Assign status to the specific claim being evaluated. These labels are not a mandatory ladder through which every artifact advances. Several claims may have different statuses at the same moment: arrival may be established while readability remains unknown. Record the evidence and limitations supporting each label.','15':'The evidence package closes the exercise by making the work inspectable. Preserve actual requests, responses, checks, and recovery observations rather than replacing them with a success narrative. These records support future integration decisions, but they do not establish untested production behavior or authorize a new release action.'}[str(n)]
  intro += " The record should make clear what was delivered, what could be read, which checks were performed, and which claims remain unsupported. Preserve the actual source and response instead of relying on a polished summary. When a check cannot be completed, name the missing evidence and limit the status accordingly. Existing authorization may permit independent work to continue, but it does not resolve the unknown by itself. Use these distinctions to decide what needs recovery and what is ready for the next authorized action."
  text(60,245,intro,17,width=1470)
  # Two columns for 10 fields; three columns for status/evidence references.
  cols=4 if n==4 else 3;cw=350 if cols==4 else 475;gap=35
  groups=[entries[i::cols] for i in range(cols)];maxbottom=0
  for col,group in enumerate(groups):
   x=60+col*(cw+gap);y=375
   for a,b in group:
    line(x,y,x+cw,y,'#B9BFC4');text(x,y+10,a,19,True);text(x,y+42,b,15,width=cw)
    lines=[];row=''
    for word in b.split():
     z=(row+' '+word).strip()
     if stringWidth(z,'Copy',15)>cw and row:lines.append(row);row=word
     else:row=z
    lines.append(row);y+=42+len(lines)*15*1.3+10
   maxbottom=max(maxbottom,y)
  if maxbottom>850:raise ValueError(f'High page {n} exceeds body: {maxbottom}')
  blocks=[('CONTEXT','',intro)]+[(a,'',b) for a,b in entries]
 count=wordcount(blocks)+len(s['title'].split())+len(s['lead'].split())
 manifest.append({'slide':n,'title':s['title'],'density':level,'editorialFeature':features[n][0],'copyWords':count,'audioAnchor':s['time'],'pattern':'visual opener' if n==1 else 'reference' if level=='high' else 'integrated editorial','diagramArrows':'reading order only, not operational authorization'})
 finish(n)
c.save()
css='*{box-sizing:border-box}body{margin:0;background:#fff;color:#20252a;font-family:Arial,Helvetica,sans-serif}.page{position:relative;width:1632px;height:1056px;background:#fff;overflow:hidden;break-after:page}.diagram{position:absolute;inset:0}.copy{position:absolute;line-height:1.3;white-space:pre-wrap;margin:0}.story{position:absolute;object-fit:contain}@page{size:17in 11in;margin:0}'
(P/'styles.css').write_text(css);(P/'BOSS_Day_Zero_Editorial_v0.3.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><title>BOSS mixed-copy companion v0.2</title><style>'+css+'</style><body>'+''.join(pages)+'</body></html>')
(P/'density-manifest.json').write_text(json.dumps(manifest,indent=2))
(P/'density-map.md').write_text('|Slide|Copy level|Words|Title|\n|---|---|---|---|\n'+'\n'.join(f'|{m["slide"]}|{m["density"]}|{m["copyWords"]}|{m["title"]}|' for m in manifest))
# Declarative source for the explanatory checkpoints; reading order is explicit.
(P/'reading-order.mmd').write_text('flowchart TB\n A["Arrival: record receipt"] -->|Next topic| B["Verification: compare evidence"]\n B -->|Next topic| C["Release: check authorization scope"]\n')
shutil.copy('draftdeck-standards/process.puml',P/'handoff.puml');shutil.copy('draftdeck-standards/process.svg',P/'handoff.svg')
(P/'REVIEW.md').write_text('DraftDeck editorial review candidate v0.3.\n15 slides with mixed low, medium, and high copy, not three duplicate 15-page decks. Source is the supplied 22-minute podcast and current Day Zero amendments. Copy adapts narration, not verbatim transcription. Dense pages expand definitions and evidence practice without adding new canonical fields. Reading-order diagrams do not authorize automatic execution; detailed conditional handoff is provided separately as PlantUML source and rendered SVG. Low and medium tiers retain live text with separate diagram geometry; opener uses separate raster artwork.\nWord counts include page headline, lead, diagram labels and teaching body; recurring navigation and writing prompt excluded. Print PDF independently composed from same coordinates, not browser export. Browser rendering and Canva compatibility untested. Ten recurring editorial features are teaching devices, not new canonical governance fields. Each slide has an integrated feature rail; the Markdown uses the same ten features. Reflection questions have no invented learner results.\n')
